# Generated by Django 5.2.15 on 2026-07-11 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sallary',
        ),
    ]
