# Generated by Django 6.0.5 on 2026-06-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=30)),
                ('day', models.CharField(max_length=20)),
                ('reservedate', models.DateField()),
            ],
        ),
    ]
