# Generated by Django 6.0.5 on 2026-06-22 20:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserve_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
