# Generated by Django 6.0.5 on 2026-06-27 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_reservation_reserve_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
