# Generated by Django 6.0.5 on 2026-06-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hiva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hiva',
        ),
    ]
