# Generated by Django 6.0.5 on 2026-06-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_foodmenu_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
