# Generated by Django 6.0.5 on 2026-06-30 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_foodmenu_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employees',
            name='location',
            field=models.CharField(choices=[('sanat', 'صنعت'), ('golchin', 'گلچین'), ('mech', 'مکانیک')], max_length=20),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='day',
            field=models.CharField(choices=[(5, 'شنبه'), (6, 'یکشنبه'), (0, 'دوشنبه'), (1, 'سه\u200cشنبه'), (2, 'چهارشنبه'), (3, 'پنجشنبه')], max_length=20),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='location',
            field=models.CharField(choices=[('sanat', 'صنعت'), ('golchin', 'گلچین'), ('mech', 'مکانیک')], max_length=30),
        ),
    ]
