# Generated by Django 5.2.15 on 2026-07-01 12:39

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_reservation_reserved_by_alter_employees_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='date',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now),
        ),
    ]
