# Generated by Django 5.2.15 on 2026-07-01 13:00

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_foodmenu_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserve_date',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now),
        ),
    ]
