# Generated by Django 5.2.15 on 2026-07-06 11:00

import django_jalali.db.models
import jdatetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_reservation_reserve_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmenu',
            name='day',
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='date',
            field=django_jalali.db.models.jDateField(default=jdatetime.date.today),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserve_date',
            field=django_jalali.db.models.jDateField(default=jdatetime.date.today),
        ),
    ]
