# Generated by Django 5.2.15 on 2026-07-06 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_foodmenu_day_alter_foodmenu_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reserve_date',
        ),
    ]
